version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/code
    ports:
    - 8000:8000
    depends_on:
    - db  
    environment:
    - DEBUG=1
    - DB_HOST=db
    - DB_NAME=django_db
    - DB_USER=postgres_user
    - DB_PASS=supersecret
  db:
    image: postgres:11
    environment:
    - POSTGRES_DB=django_db
    - POSTGRES_USER=postgres_user
    - POSTGRES_PASSWORD=supersecret
    volumes:
    - postgres_data:/var/lib/postgresql2/data/
volumes:
    postgres_data: