# Generated by Django 2.2.6 on 2019-10-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20191004_0623'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchange',
            unique_together={('currency', 'exchange_date')},
        ),
    ]
